[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.filesystem = littlefs

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D PLATFORM_ESP32

build_src_filter =
    +<*>
    -<platform/windows/>
    -<cloud/windows/>
    -<network/windows/>


lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    adafruit/Adafruit NeoPixel@^1.12.3